meta_product_name: "Loquence"
meta_title: "Loquence - data driven decision making"
meta_description: "Automated live reporting for your online shops."
meta_image: "loquence.png" # should exist in `app/assets/images/`
